assets: AAPL, MSFT # comma seperated values: AAPL, @DOGE, MSFT
streamer: dummy # options are: dummy, yahoo, polygon, alpaca
broker: paper # options are: paper, alpaca
# secret: secret.yaml # path to a file holding polygon or alpaca api tokens if needed
# basic_account: y # For polygon or alpaca, whether the accounts are the basic tier or not; options are: y, n
# alpaca_paper_trader # For alpaca only, whether to use alpaca's paper trader or to trade live, options are y, n